env: "local"
storage_path: "postgres://postgres:postgres@localhost:5433/shorturl_db"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
max_conns: 10
min_conns: 2
max_conn_lifetime: time.Hour
max_conn_idleTime: time.Minute * 30